
server:
  port=8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: root
    password: rfsql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.138.129

mybatis.mapper-locations:
  classpath:mapper/*.xml