
server:
  port=8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_demo
    username: root
    password: rfsql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.138.129
#    lettuce:
#      pool:
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: 100  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8  # 连接池中的最大空闲连接
#        min-idle: 0  # 连接池中的最小空闲连接

mybatis.mapper-locations:
  classpath:mapper/*.xml